# Generated by Django 3.1.4 on 2021-01-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosana_products_category', '0001_initial'),
        ('rosana_products', '0002_auto_20210107_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='rosana_products_category.ProductsCategory', verbose_name='دسته بندی'),
        ),
    ]
