# Generated by Django 3.1.4 on 2021-01-09 23:54

from django.db import migrations, models
import rosana_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('rosana_products', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': ' تصاویر'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=rosana_products.models.upload_gallery_image_path, verbose_name='تصویر'),
        ),
    ]
