# Generated by Django 3.1.4 on 2021-01-14 20:46

from django.db import migrations, models
import rosana_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('rosana_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rosana_setting.models.upload_image_path, verbose_name='تصویر لوگو'),
        ),
    ]
