# Generated by Django 3.1.4 on 2021-01-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': ' دسته بندی ها  ',
            },
        ),
    ]
