# Generated by Django 3.1.4 on 2021-01-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosana_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
