# Generated by Django 3.1.4 on 2021-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=20, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده / خوانده نشده')),
            ],
        ),
    ]
