# Generated by Django 3.1.4 on 2021-01-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosana_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'ارتباط با ما'},
        ),
    ]
